import type { Metadata } from "next";
import { Geist, Geist_Mono, Domine } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ToasterProvider from "@/components/ToastPreview/ToastPreview";
import "aos/dist/aos.css";
import AOSProvider from "@/components/AOSProvider/AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const domine = Domine({
  variable: "--font-domine",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${domine.variable} antialiased`}>
        <AOSProvider>
          <Header />

          <ToasterProvider />

          <main>{children}</main>

          <Footer />
        </AOSProvider>
      </body>
    </html>
  );
}
